# Site settings
title: Shared Resoures
search_enabled: true
baseurl: /common-components-wiki
url: https://bcgov.github.io
permalink: /:title

# Build settings
exclude: [README.md]
markdown: kramdown
remote_theme: pmarsceill/just-the-docs
