# Site settings
title: Shared Resources
search_enabled: true
baseurl: /common-components-wiki
url: https://bcgov.github.io
permalink: /:title

# Build settings
exclude: [README.md, CODE-OF-CONDUCT.md, CONTRIBUTING.md]
markdown: kramdown
remote_theme: pmarsceill/just-the-docs
